apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: synapse-deployment
  labels:
    component: "synapse"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: "synapse"
    spec:
      containers:
        - name: synapse
          image: "builditdigital/synapse:demo"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
          env:
              - name: NODE_ENV
                value: development
              - name: SERVER_CONF
                value: "{eolasUrl: 'http://eolas.kube.local:30934/'}"
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-svc
  labels:
    component: "synapse"
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    component: "synapse"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: synapse-ingress
spec:
  rules:
  - host: synapse.kube.local
    http:
      paths:
      - path: /
        backend:
          serviceName: synapse-svc
          servicePort: 80
