export const FETCH_PROJECTION_REQUEST = 'FETCH_PROJECTION_REQUEST';
export const FETCH_PROJECTION_SUCCESS = 'FETCH_PROJECTION_REQUEST';
export const SAVE_PROJECTION_REQUEST = 'SAVE_PROJECTION_REQUEST';
export const SET_MESSAGE = 'SET_MESSAGE';
export const RESET_PROJECT = 'RESET_PROJECT';
