image:
  repository: 006393696278.dkr.ecr.us-east-1.amazonaws.com/synapse
  tag: "latest"
  pullPolicy: Always
service:
  hostName: synapse.stage.riglet
app:
  eolasUrl: http://eolas.stage.riglet/
  authUrl: http://heimdall.stage.riglet/
  noauth: false

