replicaCount: 1
image:
  repository: builditdigital/synapse
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  hostName: synapse.kube.local
  authUrl: http://heimdall-staging-heimdal.default.svc.cluster.local/valid?unauthCode=200
app:
  eolasUrl: http://eolas.stage.kube.local/
  authUrl: http://heimdall.stage.kube.local/
  noauth: false
